### ISSUE TITLE
Does not change the status bar color on the first page (iOS)

### ISSUE THREAD

**Issue by raefa** [burkeholland/nativscript-statusbar#2]
Thanks for the module. Much easier than the old alternatives!

I may be doing something wrong here but this worked great for me on subsequent pages, but on the "start" page (where I added the module) it did not work. I note that I don't have an ActionBar on the start page and I am combining it with BackgroundSpanUnderStatusBar on that page.

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:x="nativescript-statusbar" loaded="loaded">
  <x:StatusBar ios:barStyle="dark" android:barStyle="#E34900" />
  ...
```

```
exports.loaded = function(args) {
  var page = args.object;
  page.backgroundSpanUnderStatusBar = true;
}
```

Any ideas how I could change the colour on this start page?

**Comment by donaldking** [comment]
Experiencing the same issue as well.

**Comment by burkeholland** [comment]
Did you try removing the ios attribute and adding the
backgroundSpanUnderStatusBar to the page XML?

**Comment by donaldking** [comment]
@burkeholland This is my set up:

`<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded"
      xmlns:x="nativescript-statusbar"
      class="mainGreen"
      backgroundSpanUnderStatusBar="true">
    <x:StatusBar ios:barStyle="light" android:barStyle="#00C0F5" />`

**Comment by raefa** [comment]
Yes. I tried that too.

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
xmlns:x="nativescript-statusbar" loaded="loaded"
backgroundSpanUnderStatusBar="true">
```

---

_Raef Akehurst_

raefakehurst@gmail.com
+61 (0)402 884 406

**Comment by burkeholland** [comment]
I assume you're getting a white status bar on iOS? What happens when you
remove the statusbar component?

**Comment by donaldking** [comment]
@burkeholland How do you remove it? since it wasn't specifically added?

**Comment by burkeholland** [comment]
I mean, without the status bar specified, does the
backgroundSpanUnderStatusBar work? If so, does it stop working when you
then add the StatusBar?

**Comment by raefa** [comment]
Hi Burke. StatusBar works with and without backgroundSpanUnderStatusBar ... just not on the first page. In the attached image I have the difference scenarios. I hope this helps. 

Top Image: 
First page of my app (intro.xml) without backgroundSpanUnderStatusBar. Status bar is white as you would expect.

Middle Image:
First page of my app (intro.xml) with backgroundSpanUnderStatusBar. Status bar text is black but you would expect it to be white.

Bottom Image: 
Login page of my app (login.xml). Same code uses as in the example above. Given it is not the firsst page the plugin seems to kick in and work because the status bar text is white.

![temp](https://cloud.githubusercontent.com/assets/665520/13334444/0995e96c-dc60-11e5-9d67-0c4621a90fe8.png)

**Comment by burkeholland** [comment]
Ah. Thank you.

It appears that iOS requires this to be done at the app delegate level. You have to set the `info.plist` (located in `app/App_Resources/iOS`) key turning off View Controller based Status Bar Appearance...

```
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
```

You then have to specify the status bar style in the app delegate....

``` typescript
import application = require("application");
class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];

    applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: NSDictionary): boolean {

        // set the status bar to light content
        UIApplication.sharedApplication().statusBarStyle = 1; 

        return true;
    }

    applicationDidBecomeActive(application: UIApplication): void {
        console.log("applicationDidBecomeActive: " + application)
    }
}
application.ios.delegate = MyDelegate;
application.start({ moduleName: "pages/home/home" });
```

**Comment by raefa** [comment]
Thanks Burke. That did the job.

For those using js rather than ts, here it is in JavaScript:

```
var AppDelegate = UIResponder.extend({
  applicationDidFinishLaunchingWithOptions: function () {
    // Set the status bar to light content
    UIApplication.sharedApplication().statusBarStyle = 1;
    return true;
  }
}, {
  name: "AppDelegate",
  protocols: [UIApplicationDelegate]
});
application.ios.delegate = AppDelegate;
```

**Comment by tjvantoll** [comment]
Just to note, if you don’t want to hardcode the `1` here, iOS does provide an enum you can use. `UIStatusBarStyle.LightContent` === `1`

**Comment by 3rror404** [comment]
`sharedApplication` is now a property.

```
UIApplication.sharedApplication().statusBarStyle = 1;
```

should now be

```
UIApplication.sharedApplication.statusBarStyle = 1;
```

Tripped me up there for a while.
