### ISSUE TITLE
forked into nativescript-systemui

### ISSUE THREAD

**Issue by farfromrefug** [burkeholland/nativscript-statusbar#22]
@burkeholland i want to thank you for your work on this. I forked your plugin into a new plugin called [```nativescript-systemui```](https://www.npmjs.com/package/nativescript-systemui). I created a new one because its supports statusbar and navigationbar. And i will add more in the future.

I hope you are ok with this!

**Comment by burkeholland** [comment]
Absolutely! Let me know if I should deprecate this repo in favor of that one. I haven't been maintaining it, so I'm happy to push this along to someone else.

**Comment by farfromrefug** [comment]
@burkeholland yes that's what i was thinking.
Do as you prefer. But i will maintain mine and it already supports all the features of your plugin.

Again thanks for your work!

**Comment by ray007** [comment]
Can't open issues at the new repository.
Where would be the place for that now?
Or did I just not find the button to start a first issue?

**Comment by farfromrefug** [comment]
@ray007 good catch will enable it will be done in 5 min
