### ISSUE TITLE
isnt compatible with webpack

### ISSUE THREAD

**Issue by ezequielzacca** [burkeholland/nativscript-statusbar#6]
The plugin doesnt work when you try to webpack bundle

**Comment by simonox** [comment]
@ezequielzacca @burkeholland 

I found the issue. 

In the ```package.json``` file you have to replace ```  "main": "statusbar.js" ``` with   ```"main": "statusbar"```. Then it is working with webpack. Maybe this can be fixed in this project.

This issue is similar to: https://github.com/NativeScript/nativescript-angular/issues/801

**Comment by tjvantoll** [comment]
Fixed with #10 and shipped to npm with version 4.0.1.
